### ISSUE TITLE
Displays only 25 Stories

### ISSUE THREAD

**Issue by andela-joyebanji** [unicodeveloper/lindaikeji-cli#2]
Running the command:

`
    lindaikeji top 30
`
yields only 25 stories.
![screen shot 2016-05-27 at 8 41 24 am](https://cloud.githubusercontent.com/assets/17027572/15601364/d97e2856-23e6-11e6-9318-0b3dd7f8b0a0.png)

**Comment by unicodeveloper** [comment]
Oops, gotta check that out. Thanks @andela-joyebanji . I wouldn't mind a PR to fix that tho 😸

**Comment by andela-joyebanji** [comment]
This PR, https://github.com/unicodeveloper/lindaikeji-cli/pull/5, should fix this. 😉

**Comment by unicodeveloper** [comment]
Once the commented issue is fixed, I'll merge it in and close this issue
